import os
import re
import sys
from pathlib import Path

import requests
from dotenv import load_dotenv

from mist_client import MistClient


BASE_DIR = Path(__file__).resolve().parent
OUTPUT_FILE = BASE_DIR / "site_codes.env"
PAGE_LIMIT = 1000


def load_settings():
    load_dotenv(BASE_DIR / ".env")

    settings = {
        "API_URL": os.getenv("API_URL", "").strip(),
        "MIST_API_KEY": os.getenv("MIST_API_KEY", "").strip(),
        "ORG_ID": os.getenv("ORG_ID", "").strip(),
    }
    missing = [name for name, value in settings.items() if not value]
    if missing:
        raise RuntimeError(
            f"Missing required value(s) in .env: {', '.join(missing)}"
        )

    return settings


def get_all_sites(client, org_id):
    path = f"/api/v1/orgs/{org_id}/sites"
    sites = []
    seen_site_ids = set()
    page = 1

    while True:
        page_sites = client.get_json(
            path, params={"limit": PAGE_LIMIT, "page": page}
        )
        if not isinstance(page_sites, list):
            raise RuntimeError("Mist returned an unexpected response for the sites list")

        new_site_count = 0
        for site in page_sites:
            site_id = site.get("id")
            if site_id and site_id not in seen_site_ids:
                sites.append(site)
                seen_site_ids.add(site_id)
                new_site_count += 1

        if len(page_sites) < PAGE_LIMIT or new_site_count == 0:
            break
        page += 1

    return sites


def make_env_key(site_name):
    normalized_name = re.sub(r"[^A-Za-z0-9]+", "_", site_name).strip("_")
    if not normalized_name:
        normalized_name = "Unnamed"
    return f"site_{normalized_name}"


def write_site_codes(sites):
    lines = ["# Generated by get_site_ids.py. Do not edit manually."]
    used_keys = set()

    for site in sorted(sites, key=lambda item: str(item.get("name", "")).casefold()):
        site_id = site.get("id")
        if not site_id:
            continue

        site_name = str(site.get("name") or "Unnamed")
        base_key = make_env_key(site_name)
        env_key = base_key
        suffix = 2
        while env_key in used_keys:
            env_key = f"{base_key}_{suffix}"
            suffix += 1

        used_keys.add(env_key)
        lines.append(f"{env_key}={site_id}")

    OUTPUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(lines) - 1


def main():
    try:
        settings = load_settings()
        client = MistClient(settings["API_URL"], settings["MIST_API_KEY"])
        sites = get_all_sites(client, settings["ORG_ID"])
        written_count = write_site_codes(sites)
        print(f"Saved {written_count} site IDs to {OUTPUT_FILE}")
    except requests.RequestException as error:
        print(f"Mist API request failed: {error}", file=sys.stderr)
        return 1
    except (OSError, RuntimeError, ValueError) as error:
        print(f"Failed: {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
